### PR TITLE
keep members of local knox hotspots

### PR DESCRIPTION
**Pull request by knaaptime**
(also keep geometries)

### CODE REVIEW

**Review by sjsrey — COMMENTED** [review]
I think this is correct, but it might be wise for us to add tests on this one to show expected behavior.

**Comment by knaaptime** [comment]
definitely, just wanted a look first

**Review by sjsrey — APPROVED** [review]

**Comment by knaaptime** [comment]
I think we should make the conscious decision not to build on W moving forward, so this uses a Graph to generate the hotspot labels, which will implicitly force libpysal>=4 moving forward (hence the 3.9 test failure)

**Comment by martinfleis** [comment]
> which will implicitly force libpysal>=4 moving forward

4.8, no?

**Comment by knaaptime** [comment]
sorry, yeah 48. I dont think thats a big deal, just wanted to flag in case someone disagrees?

**Comment by jGaboardi** [comment]
> sorry, yeah 48. I dont think thats a big deal, just wanted to flag in case someone disagrees?

I'm all in.

**Comment by martinfleis** [comment]
The minimal CI env was not updated to libpysal 4.8 and is now failing on main (and also failed here).

**Comment by knaaptime** [comment]
yeah i want to do the CI in a separate commit, but needed this merged for a project we're working on. Will get the tests done shortly but i think its gonna be a messier diff

**Pull request merged**
