### PR TITLE
bump to v2.3.0

### PR DESCRIPTION
**Pull request by weikang9009**
https://github.com/pysal/pointpats/issues/93

### CODE REVIEW

**Comment by weikang9009** [comment]
@ljwolf Can you check if the API for the distance-based functions is correct? If yes, I will push for a release of pointpats 2.3.0

**Comment by martinfleis** [comment]
Hmm, we should probably update the versioning tools so this gets retrieved from the tag. @jGaboardi Is setuptools_scm where we're going now?

**Comment by martinfleis** [comment]
To clarify - it is not strictly needed but the tooling we have elsewhere allows you to just add the tag and the version is fetched from that.

**Comment by ljwolf** [comment]
Yes, as far as I can tell, the API for the distance statistics is correct, and shows up correctly in the doc build! Go ahead and tag + release on PyPI!

**Comment by martinfleis** [comment]
PyPI release should happen automatically once the tag is pushed via https://github.com/pysal/pointpats/blob/main/.github/workflows/release_and_publish.yml.

**Pull request merged**
