### PR TITLE
DOC: fix API docs

### LINKED ISSUE #84: pointpats.random not in the API docs
While working on https://github.com/geopandas/geopandas/pull/2363, I've noticed that the random module is not part of the API docs. Can we make a quick PR and a release to ensure it is there and geopandas can link to it?

### PR DESCRIPTION
**Pull request by martinfleis**
Closes #84

### CODE REVIEW

**Review by jGaboardi — APPROVED** [review]
LGTM :shipit:

**Comment by jGaboardi** [comment]
As a side note, seems like the CI build for `pointpats` has been entirely disabled for sometime now.

**Comment by martinfleis** [comment]
It has never been set up in the first place apparently :D. -> #86

**Comment by jGaboardi** [comment]
> It has never been set up in the first place apparently :D. -> #86

If only there were more hours the day!

**Pull request merged**
