### PR TITLE
Fix support truncation and remove superfluous content

### PR DESCRIPTION
**Pull request by ljwolf**
This addresses a few of the recent issues filed (#100 #101 #83). The shaping issue was caused by premature truncation for the `j()` function when running `j_test()`. For `j_test()`, we need to keep *all* support values of the `j()` function until the end, and *then* truncate. 

The other superfluous files, such as `ripley.py` and deprecated statistics, are removed, too.

### CODE REVIEW

**Comment by weikang9009** [comment]
@ljwolf Thanks for fixing this! It seems that `test_j()` did not pass?

**Comment by ljwolf** [comment]
Yep, still working. Wait til the tests pass to merge 😄

**Comment by martinfleis** [comment]
@ljwolf do you think this could make it to the next meta? We need to cut a release anyway due to #107 so it would be nice to clean these deprecations.

**Comment by martinfleis** [comment]
We'll also need to sync this and #109 but I can update #109 easily once this is in.

**Review by martinfleis — APPROVED** [review]
lgtm

**Review by jGaboardi — APPROVED** [review]

**Pull request merged**
